[Greeter]
background=/usr/share/backgrounds/caramos/default.png
draw-user-backgrounds=false
theme-name=Cinnamon-Delight
icon-theme-name=Tela-circle-light
cursor-theme-name=Bibata-Modern-Classic
font-name=Be Vietnam Pro 11
